/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Obsidian Nexus color tokens (from DESIGN.md + reference HTML)
        'on-primary-fixed': '#050505',
        'on-secondary-fixed': '#002113',
        'secondary': '#4edea3',
        'on-secondary-container': '#00311f',
        'secondary-fixed': '#6ffbbe',
        'surface-container-lowest': '#020202',
        'on-primary': '#050505',
        'on-tertiary-container': '#272a2c',
        'secondary-fixed-dim': '#4edea3',
        'on-surface-variant': '#c7c4d7',
        'on-primary-fixed-variant': '#1a1a1a',
        'on-surface': '#dae2fd',
        'secondary-container': '#00a572',
        'error-container': '#93000a',
        'inverse-primary': '#f4f3ef',
        'on-error': '#690005',
        'outline-variant': '#464554',
        'surface-container-highest': '#1a1a1a',
        'error': '#ffb4ab',
        'primary-container': '#1a1a1a',
        'surface': '#050505',
        'surface-bright': '#222222',
        'tertiary-fixed': '#e0e3e5',
        'on-background': '#dae2fd',
        'on-tertiary-fixed-variant': '#444749',
        'surface-container': '#0f0f0f',
        'surface-tint': '#f4f3ef',
        'on-tertiary': '#2d3133',
        'primary-fixed': '#f4f3ef',
        'tertiary-container': '#8e9193',
        'inverse-on-surface': '#283044',
        'outline': '#908fa0',
        'on-tertiary-fixed': '#191c1e',
        'on-primary-container': '#050505',
        'primary-fixed-dim': '#e6e2db',
        'on-secondary-fixed-variant': '#005236',
        'on-secondary': '#003824',
        'surface-variant': '#1a1a1a',
        'background': '#050505',
        'tertiary-fixed-dim': '#c4c7c9',
        'primary': '#f4f3ef',
        'surface-dim': '#050505',
        'tertiary': '#c4c7c9',
        'surface-container-low': '#0d0d0d',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dae2fd',
        'surface-container-high': '#141414',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.375rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'base': '4px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'gutter': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'sans': ['Geist', 'system-ui', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'code-block': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'code-block': ['14px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
